name: Feature request
description: Suggest an improvement to sieve
title: "[feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
